services:
  backend:
    build: ./services/backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/workspace/backend
    working_dir: /workspace/backend/ajlog/src
    command: fastapi dev --host 0.0.0.0 --port 8080 main.py
  frontend:
    build: ./services/frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/workspace/frontend
    working_dir: /workspace/frontend/ajlog
    command: npm run dev
