services:
  backend:
    build: ./services/backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/workspace/backend
    command: sleep infinity
  frontend:
    build: ./services/frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/workspace/frontend
    command: sleep infinity
