// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/contacts/:contactId": {
    params: {
      "contactId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/contacts/:contactId";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contacts/:contactId";
  };
};